spring:
  application:
    name: library-management
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

---
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: ${H2_URL}
    username: ${H2_USER}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
